### ISSUE TITLE
现在还提供从下载好的小说中生成电子书的功能吗？

### ISSUE THREAD

**Issue by wby238** [LZ0211/Wedge#4]
上一个Node-Ebk提供了convertEbook()，但目前好像还没发现在的项目现类似的功能……

**Comment by LZ0211** [comment]
那个功能只是个语法糖而已，这个版本的为了提高效率，电子书生成功能是开启新的子进程来实现的。
我会考虑以插件的形式加上，你也可以用lib/ebook/cli.js来运行，这是个命令行程序
node cli -f [formation] -i [input] -o [output]
-f 书籍格式
-i 原始文件路径
-o 电子书保存路径
比如 node cli -f epub -i E:\MyBooks\Library\books\3781994f-081f-dc0d-6275-08bd116f1751 -o E:\MyBooks\ebooks

如果要直接通过App执行的话，可以设置ebook.activated=true
然后执行App.CMD('loadBook > generateEbook > end')(dir)
封装一下就是你要的convertEbook()

**Comment by wby238** [comment]
OK，thx

**Comment by LZ0211** [comment]
如果要直接通过App执行的话，可以设置ebook.activated=true
然后执行App.CMD('loadBook > generateEbook > end')(dir)
封装一下就是你要的convertEbook()

**Comment by wby238** [comment]
好像出错了……转chm时出错的……

log：
```js
F:\git\Wedge\lib\ebook\cli.js:21
        generator(bookData,function (data){
        ^

TypeError: generator is not a function
    at F:\git\Wedge\lib\ebook\cli.js:21:9
    at endFun.forEach.item (F:\git\Wedge\lib\Thread.js:47:34)
    at Array.forEach (native)
    at end (F:\git\Wedge\lib\Thread.js:47:20)
    at doExcute (F:\git\Wedge\lib\Thread.js:26:37)
    at Immediate.setImmediate (F:\git\Wedge\lib\Thread.js:21:34)
    at runCallback (timers.js:666:20)
    at tryOnImmediate (timers.js:639:5)
    at processImmediate [as _immediateCallback] (timers.js:611:5)
```

顺便问一下转chm的话会将下载的章节图片一起放入chm吗？
还有就是能否加入将章节中的图片放入支持图片格式的电子书这个功能吗？（例如epub）

**Comment by LZ0211** [comment]
因为chm不是跨平台的兼容格式，所以已经从电子书格式中去除了。
